export const ADD_PRODUCT = 'ADD_PRODUCT';
export const LIST_DEALBOARD = 'LIST_DEALBOARD';
export const SELECTONE_DEALBOARD='SELECTONE_DEALBOARD';
export const DELETEONE_DEALBOARD='DELETEONE_DEALBOARD';
export const UPDATE_DEALBOARD='UPDATE_DEALBOARD';
export const ADD_DEALBOARD= 'ADD_DEALBOARD';
